server:
  port: 8083
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 111
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  configuration:
    mapUnderscoreToCamelCase: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
