server:
  port: 9195
  ssl:
    key-store: classpath:ezpark114514.jks
    key-store-password: 
    key-store-type: JKS

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user?characterEncoding=utf-8&serverTimezone=UTC
    username: r3432434
    password: 21323123
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  configuration:
    mapUnderscoreToCamelCase: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
